name: Pruebas automáticas del grupo
 
on:
  push:
    branches:
      - main
      - '*' # Ejecuta en cualquier rama
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        # Se recomienda usar la versión más reciente
        uses: actions/checkout@v4 
 
      - name: Configurar Python
        # Se recomienda usar la versión más reciente
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
 
      - name: Instalar dependencias
        run: |
          pip install pytest
      
      - name: Ejecutar pruebas
        run: |
          pytest -v
